version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: sellit-backend

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    container_name: sellit-frontend
    depends_on:
      - backend
